name: Continuous Integration
on:
  pull_request:
    branches:
      - "**"
  push:
    branches:
      - main
    tags:
      - "*"
jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: yarn
      - name: Test and coverage
        run: yarn jest --coverage
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.FRONTEND_SONARCLOUD_TOKEN }}
